### ISSUE TITLE
AngularJS integration

### ISSUE THREAD

**Issue by erperejildo** [truffls/react-in-angular#1]
I've got an old project running on AngularJS 1.5 and on a different folder, another project running on React 16 (latest version).

How does my AngularJS project know about React, which is on a different location?

If I try to add `click-me-button`, it doesn't exist on AngularJS. These projects are completely different. How can they interact each other? Maybe I'm missing something really stupid here, sorry

**Comment by floriangosse** [comment]
You have to wrap you React component and register it as Angular component. Have you tried to follow the example in the Readme?

**Comment by erperejildo** [comment]
But when you have your React component, where do you have that? You have 2 projects running at the same time? That's what I don't really understand.

At the moment I've got 2 different folder: one on AngularJS and the other one on React. One working on `localhost:4200` and another one on `localhost:8080`.

How can I link both projects?

I also understand at the end we'll have just AngularJS project running with these React components working inside?

**Comment by floriangosse** [comment]
> But when you have your React component, where do you have that? You have 2 projects running at the same time? That's what I don't really understand.

You have just one project. The AngularJS application works as the master/root of the application and renders React components as children.

> I also understand at the end we'll have just AngularJS project running with these React components working inside?

Yes, you have a React component which you wrap with `react-in-angular` and you register the result as an AngularJS component.

If you want you can use the root component of your React application, wrap it with `react-in-angular`, make it accessible in the AngularJS context and render it in the template.

Example:

**Application.jsx** *– root of our React application*
```jsx
const React = require('React');

// ...

const Application = () => {
    return (
        // ... your react component tree
    );
};
```

**module.js** *– part of our AngularJS application*
```js
const angular = require('angular');
const ReactApplication = require('./Application.jsx');

// ...

angular.module('my-module', [])
    .component('reactApplication', toComponent()(ReactApplication, {}));
```

**template.html** *– part of our AngularJS application*
```html
<!-- ... -->
<react-appication></react-application>
<!-- ... -->
```

This is how you can render a whole React application inside of an AngularJS application. You don't have two servers which render both applications separately instead you import the React application into your AngularJS application and make use of `react-in-angular`.

**Comment by erperejildo** [comment]
Fair enough. 

I tried first creating 2 separe projects with each framework and it was a bit confusing. Thanks for clarifying.

**Comment by floriangosse** [comment]
No problem. If you have more questions feel free to ask. :)
